version: "3"

services:  
  runner:
    build: .
    depends_on:
      - database
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ALCHEMY_API_KEY=${ALCHEMY_API_KEY}

  database:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  data: