//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "fighter")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub wisdom_point: i32,
    pub strength_from: i32,
    pub strength_to: i32,
    pub attack_from: i32,
    pub attack_to: i32,
    pub defence_from: i32,
    pub defence_to: i32,
    pub omega_from: i32,
    pub omega_to: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
