//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "fighter_parent")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub fighter_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub parent_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::fighter::Entity",
        from = "Column::FighterId",
        to = "super::fighter::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Fighter2,
    #[sea_orm(
        belongs_to = "super::fighter::Entity",
        from = "Column::ParentId",
        to = "super::fighter::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Fighter1,
}

impl ActiveModelBehavior for ActiveModel {}
