//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "fighter_trait")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub fighter_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub trait_type: String,
    pub value: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::fighter::Entity",
        from = "Column::FighterId",
        to = "super::fighter::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Fighter,
}

impl Related<super::fighter::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Fighter.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
