//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "meta_failed_tournament_request")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub page_size: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub page_index: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
