//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

pub mod prelude;

pub mod fighter;
pub mod fighter_parent;
pub mod fighter_trait;
pub mod meta_failed_tournament_request;
pub mod tournament;
pub mod tournament_warrior;
