//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub mod prelude;

pub mod fighter;
pub mod fighter_parent;
pub mod fighter_trait;
pub mod meta_failed_tournament_request;
pub mod meta_last_page;
pub mod sea_orm_active_enums;
pub mod tournament;
pub mod tournament_detail_attack;
pub mod tournament_detail_champion;
pub mod tournament_detail_round;
pub mod tournament_warrior;
