//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

pub mod prelude;

pub mod fighter;
pub mod fighter_parent;
pub mod fighter_trait;
pub mod tournament;
pub mod tournament_solo_warrior;
pub mod tournament_warrior;
