//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tournament")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub service_id: i32,
    pub currency: Vec<u8>,
    pub fee_percentage: i32,
    pub buy_in: Vec<u8>,
    pub top_up: Vec<u8>,
    pub key: String,
    pub legacy: Option<bool>,
    pub level: String,
    pub modified: DateTime,
    pub name: Option<String>,
    pub restrictions: Json,
    pub solo_optionals: Option<Json>,
    pub start_time: DateTime,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl Related<super::fighter::Entity> for Entity {
    fn to() -> RelationDef {
        super::tournament_warrior::Relation::Fighter.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::tournament_warrior::Relation::Tournament.def().rev())
    }
}

impl Related<super::fighter::Entity> for Entity {
    fn to() -> RelationDef {
        super::tournament_solo_warrior::Relation::Fighter.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::tournament_solo_warrior::Relation::Tournament
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
