//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tournament_detail_round")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub tournament_id: i64,
    pub tournament_service_id: i64,
    pub round: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tournament::Entity",
        from = "Column::TournamentId",
        to = "super::tournament::Column::ServiceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Tournament,
    #[sea_orm(has_many = "super::tournament_detail_attack::Entity")]
    TournamentDetailAttack,
}

impl Related<super::tournament::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tournament.def()
    }
}

impl Related<super::tournament_detail_attack::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TournamentDetailAttack.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
