//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tournament_warrior")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub tournament_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub warrior_id: i64,
    pub account: Option<Vec<u8>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::fighter::Entity",
        from = "Column::WarriorId",
        to = "super::fighter::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Fighter,
    #[sea_orm(
        belongs_to = "super::tournament::Entity",
        from = "Column::TournamentId",
        to = "super::tournament::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Tournament,
}

impl Related<super::fighter::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Fighter.def()
    }
}

impl Related<super::tournament::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tournament.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
